### PR TITLE
fix(config): use the config `default_channel` field as a fallback when no channel is specified

### LINKED ISSUE #520: default_channel throws error in config.toml
**Description**
Using the `default_channel` field in the main `config.toml` file throws the following error:
```
Error: Error parsing configuration file: /home/different/.config/television/config.toml

╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║  If this follows a recent update, it is likely due to a breaking change in   ║
║  the configuration format.                                                   ║
║                                                                              ║
║  Check https://github.com/alexpasmantier/television/releases/latest for the  ║
║  latest release notes.                                                       ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

Caused by:
    TOML parse error at line 1, column 1
      |
    1 | default_channel = "nixpkgs"
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    unknown field `default_channel`
```

**Example**
`~/.config/television/config.toml`
```toml
default_channel = "nixpkgs"
```

**Expected behavior**
To be able to set the default channel, as per
https://github.com/alexpasmantier/television/blob/7bbf5388984ea4a9afa4daad695add4c258c0fb1/.config/config.toml#L20

**Actual behavior**
Using the `default_channel` results in a config parsing error

**Environment**
 - OS: NixOS
 - Rust version: 1.86.0
 - Project version: 0.11.9

### PR DESCRIPTION
**Pull request by alexpasmantier**
Fixes #520 

fyi @lalvarezt

### CODE REVIEW

File: television/main.rs [hunk 1]
```diff
@@ -156,35 +149,47 @@ pub fn handle_subcommands(command: &Command, config: &Config) -> Result<()> {
...
-        Ok(channel_prototype)
+        channel_prototype
     } else {
-        debug!("Using {:?} channel", args.channel);
-        Ok(args.channel)
+        let channel = args
+            .channel
+            .as_ref()
+            .unwrap_or(&config.application.default_channel)
+            .clone();
```
Comment (alexpasmantier) [inline television/main.rs:175]: @lalvarezt this is the fix 👍🏻
