### PR TITLE
fix(actions): fix execute/fork actions when tv runs under shell integration

### LINKED ISSUE #997: Edit action in `files` channel does not work if run via shell integration
**Description**
`tv` has a nice feature of [opening selected files in editor](https://github.com/alexpasmantier/television/blob/f937ebb15e65aa118fdbb34329c03d1768d992f8/cable/unix/files.toml#L15).
That works fine unless `tv` is run with a shell shortcut (`ctrl-t` by default).
In that case the whole terminal window freezes and can only be killed from that point.

**Example**
Good behaviour: just run `tv` and hit `f12` (default) to open in `$EDITOR`.
Bad behaviour: `source $(tv init fish)` (or `bash`), hit `ctrl-t` and then hit `f12` -- terminal freezes.
This can also be reproduce with a simpler `set selected $(tv)` line (with following `f12`).
The bug is reproduced both in fish and bash.

I checked this behaviour against `fzf` to exclude `fish`-specific problems. `fzf` works correctly in a similar scenario:
```fish
set result (fzf --bind 'f12:execute(nvim {})') # nvim opens normally.
```
 

**Expected behavior**
Editor and other programs should open normally regardless of how `tv` was started.

**Environment**

- OS: NixOS
- TV version: 0.15.4
- shell: fish
- terminal: kitty

### PR DESCRIPTION
**Pull request by lalvarezt**
## 📺 PR Description

This PR closes #997 

It reattaches external action stdio to `/dev/tty` on Unix before exec or spawn, so actions launched from shell integration use the real terminal instead of inheriting command-substitution pipes

## Checklist

- [x] my commits **and PR title** follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [ ] if this is a new feature, I have added tests to consolidate the feature and prevent regressions
- [x] if this is a bug fix, I have added a test that reproduces the bug (if applicable)
- [x] I have added a reasonable amount of documentation to the code where appropriate

### CODE REVIEW

File: tests/cli/external_actions.rs [hunk 1]
```diff
@@ -151,3 +152,158 @@ mode = "execute"
     // Check that the process has finished
     PtyTester::assert_exit_ok(&mut child, DEFAULT_DELAY);
 }
+
+#[test]
+fn test_execute_action_uses_tty_when_stdout_is_captured() {
+    let mut tester = PtyTester::new();
+
+    let cable_dir = TempDir::new().unwrap().path().join("captured_stdout");
+    fs::create_dir_all(&cable_dir).unwrap();
```
Comment (alexpasmantier) [inline tests/cli/external_actions.rs]: I think the `cable_dir` never gets cleaned up here because the tempdir is dropped immediately.
You probably need to:
```rs
let temp_dir = ...;
let cable_dir = ...;
```

File: tests/cli/external_actions.rs [hunk 2]
```diff
@@ -151,3 +152,158 @@ mode = "execute"
...
+        output
+    );
+}
+
+#[test]
+fn test_fork_action_uses_tty_when_stdout_is_captured() {
+    let mut tester = PtyTester::new();
+
+    let cable_dir =
+        TempDir::new().unwrap().path().join("captured_stdout_fork");
```
Comment (alexpasmantier) [inline tests/cli/external_actions.rs]: same thing here

**Review by alexpasmantier — COMMENTED** [review]
Great job investigating this 👍🏻 
Thanks for the fix.
Left a minor comment, but otherwise lgtm!

PS: sorry for the delay

File: tests/cli/external_actions.rs (hunk 1 above)
Comment (lalvarezt) [reply tests/cli/external_actions.rs]: you're right, fixed

**Comment by alexpasmantier** [comment]
Thanks for the fix 😁
